### ISSUE TITLE
Add way to reset input

### ISSUE THREAD

**Issue by tomiiide** [drac94/react-auth-code-input#15]
There should be a function or way to reset the input.

**Comment by drac94** [comment]
Hi @tomiiide thanks for the suggestion, could you create a use case for how this would be used? Also, any PR is welcomed! :)

**Comment by james-Infotrack** [comment]
I've got a use case, where if they get the code wrong, we want to reset the field, 

the way I've solved it is remounting the component with a new Key @tomiiide  maybe try that. 

```             
 <AuthCode
      key={downloadMountKey}
      characters={6}
      onChange={(value: string) => {
        setDownloadCode(value);
       }}
   ```
                
                
                ```
                
  const resetFields = () => {
    // reset our data
    setDownloadCode('');
 
    const resetKey1 = Math.random().toString().slice(0.8);
    
    setDownloadMountKey(resetKey1);
  
  };```
