### ISSUE TITLE
Add a ref to the first input

### ISSUE THREAD

**Issue by eladonline** [drac94/react-auth-code-input#24]
I want to auto focus and cant do it in react way 
add a ref for focus

**Comment by drac94** [comment]
Hi @eladonline, the first input should already be focused when the component is mounted. If it is not the case could you provide an example of it not working as intended? or maybe you have another use case not covered by it?

**Comment by eladonline** [comment]
I want to handle my own auto focus like when clicking a button it focus the input

**Comment by eladonline** [comment]
whould be nice just to expose the ref so itll be more generic

**Comment by drac94** [comment]
@eladonline I just created the branch https://github.com/drac94/react-auth-code-input/tree/v3.1.0 with this implemented, would be helpful if you could test it.

**Comment by drac94** [comment]
solved in v3.1.0
