### ISSUE TITLE
Add option to clear the input

### ISSUE THREAD

**Issue by calin-stan** [drac94/react-auth-code-input#37]
Hello, I have just integrated this package, and I noticed that there is no way to clear the inputs programmatically. This would be useful as the code that the user types may be invalid and it would help them if they had a "clear" button somewhere on the page instead of manually having to do so.

**Comment by drac94** [comment]
Hi @calin-stan there is a workaround that you can use to achieve what you want, it is mentioned here https://github.com/drac94/react-auth-code-input/issues/15

**Comment by drac94** [comment]
solved in v3.1.0

**Comment by calin-stan** [comment]
Great job! It works like a charm, thank you.
