### ISSUE TITLE
How to style it ?

### ISSUE THREAD

**Issue by malatini42** [drac94/react-auth-code-input#44]
Hello ! I did not understand how I can style it ? My height is quite small. Thanks a lot for your work.

**Comment by drac94** [comment]
Hi @malatini42 you can see an example here https://github.com/drac94/react-auth-code-input/blob/master/example/src/index.css

**Comment by malatini42** [comment]
Ok thanks a lot ! I have two arrows on each box and I do not know how to get rid of it, could you tell me please ? thanks again

**Comment by malatini42** [comment]
<img width="159" alt="Screenshot 2022-04-15 at 13 40 16" src="https://user-images.githubusercontent.com/77189438/163566673-c7353d77-0a48-4b1e-895b-bd71ef397649.png">

**Comment by drac94** [comment]
@malatini42 you can remove them using css, here is an example https://css-tricks.com/snippets/css/turn-off-number-input-spinners/

**Comment by malatini42** [comment]
Ok thanks a lot !
