### ISSUE TITLE
When using the allowedCharacters='numeric', allows you to enter spaces

### ISSUE THREAD

**Issue by kit52** [drac94/react-auth-code-input#56]
`    <AuthCode
          onChange={onChange}
          containerClassName='pin-input'
          length={4}
          allowedCharacters='numeric'
        />`

**Comment by drac94** [comment]
Does this still happen? which browser? which version?

**Comment by kit52** [comment]
> Does this still happen? which browser? which version?

I dont know, i write  my component and dont use this library
