### ISSUE TITLE
Can't style inputs

### ISSUE THREAD

**Issue by mark-bt** [drac94/react-auth-code-input#58]
Running React 18 the inputs are not being styled. Now that inputStyle is no more, how can we style the inputs?

![image](https://user-images.githubusercontent.com/69472831/213576134-47e3c1b1-189c-469f-8210-16869f593d10.png)

`
    <AuthCode
          onChange={(e) => {
            onChange(e);
          }}
          length={6}
          allowedCharacters="numeric"
          inputClassName="input"
          containerClassName='container'
      />
`

**Comment by drac94** [comment]
Maybe a dumb question, but are you declaring and importing your CSS classes? I put here a working example https://codesandbox.io/s/infallible-neumann-yvmq27?file=/src/App.js

**Comment by mark-bt** [comment]
This did it. Thank you very much!
